### ISSUE TITLE
Couldn't load plugin 'network_gt' due to an error when calling its classFactory() method  

### ISSUE THREAD

**Issue by kaford315** [BjornNyberg/NetworkGT#14]
Hi Bjorn, 

Just opened up NetworkGT today and it's running this error: 

Couldn't load plugin 'network_gt' due to an error when calling its classFactory() method 

ImportError: C extension: No module named 'pandas._libs.tslibs.conversion' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first. 

I've tried updating plotly and pandas but this hasn't helped. Any ideas? 

Thanks!

**Comment by BjornNyberg** [comment]
@kaford315 

Strange.... this is definately related to pandas. A quick google search would suggest that you uninstall pandas entirely and reinstall (https://stackoverflow.com/questions/54093020/no-module-named-pandas-libs-tslib)

  `pip uninstall pandas
  pip install pandas `

Does this solve your problem?

**Comment by kaford315** [comment]
Hi Bjorn,


I did try this already and unfortunately no luck! I'll keep searching


Katie

________________________________

**Comment by ElcoLuijendijk** [comment]
I also have this issue with the latest version of QGIS. It is actually an issue with numpy and not NetworkGT/pandas. 
When opening the console and trying to import numpy, this is the response:

`import numpy
Traceback (most recent call last):
  File "/Users/elcopone/opt/miniconda3/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elcopone/opt/miniconda3/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elcopone/opt/miniconda3/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elcopone/opt/miniconda3/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/Applications/QGIS3.16.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elcopone/opt/miniconda3/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Applications/QGIS3.16.app/Contents/MacOS/QGIS"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'`

I am using numpy 1.19.2 on mac osx 10.14.6

One solution may be to downgrade qgis to an older version, since that uses an older version of python. Am trying that now

**Comment by BjornNyberg** [comment]
@ElcoLuijendijk and @kaford315 

Did either of you solve this problem? I can not find the route of the problem.

**Comment by hoetmaaiers** [comment]
Any feedback on how you solved this?
